// Last updated: 10/9/2026, 10:04:19 AM
1class Solution {
2    public List<Integer> preorder(Node root) {
3        // To store the output array...
4        List<Integer> output = new ArrayList<Integer>();
5        // Base case: if the tree is empty...
6        if (root == null) return output;
7        // Create a stack of Node and push root to it...
8        Stack<Node> st = new Stack<>();
9        st.push(root);
10        // Traverse till stack is not empty...
11        while (!st.isEmpty()) {
12            // Pop a Node from the stack and add it to the output list...
13            Node node = st.pop();
14            output.add(node.val);
15            // Push all of the child nodes of the node into the stack from right to left...
16            // Push from right to left to get the right preorder traversal...
17            for (int idx = node.children.size() - 1; idx >= 0; idx--) {
18                Node child = node.children.get(idx);
19                st.push(child);
20            }
21        }
22        return output;      // Return the output...
23    }
24}